#!/usr/bin/env python3
"""
D2 Production Backend — V20 Spectral Layer-wise Quant Planner
"""
import numpy as np
import json
from typing import List, Dict

DTYPES = ["FP16", "INT8", "INT4"]
DTYPE_BYTES = {"FP16": 2.0, "INT8": 1.0, "INT4": 0.5}
TPS_GAIN = {"FP16": 1.0, "INT8": 1.35, "INT4": 1.75}
RISK_BASE = {"FP16": 0.2, "INT8": 0.6, "INT4": 1.2}


def spectral_features_sim(shape: List[int], name: str = "") -> Dict:
    """Simulate spectral features for a layer."""
    m, n = shape
    size = m * n
    if "lm_head" in name.lower() or size > 400_000_000:
        return {
            "stable_rank": 110,
            "spectral_entropy": 4.1,
            "tail_index": 1.35,
            "outlier_mass": 0.65
        }
    elif any(x in name.lower() for x in ["mlp", "gate", "up", "down"]):
        return {
            "stable_rank": 48,
            "spectral_entropy": 3.3,
            "tail_index": 1.75,
            "outlier_mass": 0.38
        }
    else:
        return {
            "stable_rank": 32,
            "spectral_entropy": 2.4,
            "tail_index": 2.3,
            "outlier_mass": 0.25
        }


def layer_score(layer: Dict, q: str, w_speed: float = 1.0, w_risk: float = 0.3) -> float:
    """Calculate quality score for a layer quantization choice."""
    size = layer["size"]
    TPS = TPS_GAIN.get(q, 1.0) * size * 1e-12 * w_speed
    risk_mult = 5.0 if layer.get("type") == "head" else 1.0
    Risk = RISK_BASE.get(q, 0.6) * np.log1p(size) * risk_mult * w_risk
    f = layer.get("spectral_features", {})
    spectral_bonus = 0.12 * (f.get("stable_rank", 30) + f.get("tail_index", 2.0))
    return TPS - Risk + spectral_bonus


def solve_quantization_plan(
    raw_layers: List[Dict],
    vram_budget_gb: float = 8.0,
    w_speed: float = 1.0,
    w_risk: float = 0.3
) -> List[Dict]:
    """Solve quantization plan with spectral analysis and VRAM constraints."""
    layers = []
    for layer in raw_layers:
        m, n = layer["shape"]
        size = m * n
        name = layer["name"]
        ltype = (
            "head" if "lm_head" in name.lower() else
            "ffn" if any(x in name.lower() for x in ["mlp", "gate", "up", "down"]) else
            "attn"
        )
        
        enriched = {
            "name": name,
            "size": size,
            "shape": layer["shape"],
            "type": ltype,
            "spectral_features": spectral_features_sim(layer["shape"], name)
        }
        layers.append(enriched)

    plan = []
    total_vram = 0.0
    for layer in layers:
        best_q = "FP16"
        best_score = -np.inf
        best_vram_add = 0.0
        
        for q in DTYPES:
            vram_layer = layer["size"] * DTYPE_BYTES[q] / 1e9
            if total_vram + vram_layer > vram_budget_gb + 0.2:
                continue
            score = layer_score(layer, q, w_speed, w_risk)
            if score > best_score:
                best_score = score
                best_q = q
                best_vram_add = vram_layer
        
        plan.append({
            "name": layer["name"],
            "layer_type": layer["type"],
            "dtype": best_q,
            "score": round(best_score, 4),
            "vram_gb": round(best_vram_add, 6)
        })
        total_vram += best_vram_add
    
    return plan


def summarize(plan: List[Dict], vram_budget: float, w_speed: float, w_risk: float) -> str:
    """Generate summary of quantization plan."""
    vram_used = sum(e["vram_gb"] for e in plan)
    counts = {}
    for e in plan:
        counts[e["dtype"]] = counts.get(e["dtype"], 0) + 1
    lines = [
        f"VRAM Budget : {vram_budget:.1f} GB",
        f"VRAM Used   : {vram_used:.3f} GB ({vram_used/vram_budget*100:.1f}%)",
        f"w_speed     : {w_speed:.2f} | w_risk : {w_risk:.2f}",
        f"Layers      : {len(plan)}",
        "\nDistribution :"
    ]
    for dtype in ["FP16", "INT8", "INT4"]:
        c = counts.get(dtype, 0)
        lines.append(f"  {dtype:4} : {c:3d} couches")
    return "\n".join(lines)


def export_gguf(plan: List[Dict], output_path: str = "quant_plan.json") -> str:
    """Export quantization plan to GGUF-compatible JSON format."""
    quant_map = [{"layer": e["name"], "dtype": e["dtype"]} for e in plan]
    data = {
        "backend": "llama.cpp",
        "quantization_map": quant_map,
        "kv_cache": "FP16",
        "vram_budget_gb": float(sum(e["vram_gb"] for e in plan)),
        "notes": "Generated by D2 V20"
    }
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
    
    return f"# llama.cpp command example:\n./llama-quantize --model base.gguf --output quantized.gguf --quantization-map {output_path}"
